#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sitecom_homepage:
  path:     /
  defaults: { _controller: App\Controller\HomeController::index }

sitecom_registrationpage:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }