#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sitecom_homepage:
  path:     /
  defaults: { _controller: App\Controller\HomeController::index }

sitecom_registrationpage:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }



sitecom_createtrick:
  path:     /addtrick
  defaults: { _controller: App\Controller\TrickController::addtrick }


sitecom_showtrick:
  path:     /showtrick/{id}
  defaults: { _controller: App\Controller\TrickController::showtrick }



sitecom_edittrick:
  path:     /edittrick/{id}
  defaults: { _controller: App\Controller\TrickController::edittrick }



sitecom_listtrick:
  path:     /listtrick
  defaults: { _controller: App\Controller\TrickController::listtrick}



